<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net$(NETCoreAppMaximumVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Framework" Version="6.0.1" />
    <PackageReference Include="Meziantou.Framework.ProcessWrapper" Version="2.0.2" />
    <PackageReference Include="Meziantou.Framework.TemporaryDirectory" Version="3.0.1" />
    <PackageReference Include="Meziantou.Framework.Threading" Version="3.1.0" />
    <PackageReference Include="Microsoft.Deployment.DotNet.Releases" Version="1.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSBuild.StructuredLogger" Version="2.3.244" />
    <PackageReference Include="NuGet.Packaging" Version="7.9.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
