// <auto-generated />
// Included by Meziantou.NET.Sdk when 'IncludeSharedHttpClient' is set to 'true'.
#nullable enable

namespace Meziantou.NET.Sdk;

internal static class SharedHttpClient
{
    private static readonly global::System.Lazy<global::System.Net.Http.HttpClient> LazyInstance = new(() => CreateHttpClient(allowAutoRedirect: false));
    private static readonly global::System.Lazy<global::System.Net.Http.HttpClient> LazyInstanceWithAutoRedirect = new(() => CreateHttpClient(allowAutoRedirect: true));

    /// <summary>Gets a shared <see cref="global::System.Net.Http.HttpClient"/> that does not follow the redirection responses.</summary>
    public static global::System.Net.Http.HttpClient Instance => LazyInstance.Value;

    /// <summary>Gets a shared <see cref="global::System.Net.Http.HttpClient"/> that follows the redirection responses.</summary>
    public static global::System.Net.Http.HttpClient InstanceWithAutoRedirect => LazyInstanceWithAutoRedirect.Value;

    private static global::System.Net.Http.HttpClient CreateHttpClient(bool allowAutoRedirect)
    {
#if NETCOREAPP2_1_OR_GREATER
        var socketHandler = new global::System.Net.Http.SocketsHttpHandler()
        {
            AllowAutoRedirect = allowAutoRedirect,
#if NETCOREAPP3_0_OR_GREATER
            // 'All' enables every method supported by the target framework, including Zstandard on .NET 11+
            AutomaticDecompression = global::System.Net.DecompressionMethods.All,
#else
            AutomaticDecompression = global::System.Net.DecompressionMethods.GZip | global::System.Net.DecompressionMethods.Deflate | global::System.Net.DecompressionMethods.Brotli,
#endif
            PooledConnectionIdleTimeout = global::System.TimeSpan.FromMinutes(1),
            PooledConnectionLifetime = global::System.TimeSpan.FromMinutes(1),
        };
#else
        var socketHandler = new global::System.Net.Http.HttpClientHandler()
        {
            AllowAutoRedirect = allowAutoRedirect,
            AutomaticDecompression = global::System.Net.DecompressionMethods.GZip | global::System.Net.DecompressionMethods.Deflate,
        };
#endif

        return new global::System.Net.Http.HttpClient(new HttpRetryMessageHandler(socketHandler), disposeHandler: true);
    }

    private sealed class HttpRetryMessageHandler : global::System.Net.Http.DelegatingHandler
    {
        public HttpRetryMessageHandler(global::System.Net.Http.HttpMessageHandler handler)
            : base(handler)
        {
        }

        protected override async global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> SendAsync(global::System.Net.Http.HttpRequestMessage request, global::System.Threading.CancellationToken cancellationToken)
        {
            const int MaxRetries = 5;
            var defaultDelay = global::System.TimeSpan.FromMilliseconds(200);
            for (var i = 1; ; i++, defaultDelay += defaultDelay)
            {
                global::System.TimeSpan? delayHint = null;
                global::System.Net.Http.HttpResponseMessage? result = null;

                try
                {
                    result = await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
                    if (!IsLastAttempt(i) && ((int)result.StatusCode >= 500 || result.StatusCode is global::System.Net.HttpStatusCode.RequestTimeout or (global::System.Net.HttpStatusCode)429 /* TooManyRequests */))
                    {
                        // Use "Retry-After" value, if available. Typically, this is sent with
                        // either a 503 (Service Unavailable) or 429 (Too Many Requests):
                        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

                        delayHint = result.Headers.RetryAfter switch
                        {
                            { Date: { } date } => date - global::System.DateTimeOffset.UtcNow,
                            { Delta: { } delta } => delta,
                            _ => null,
                        };

                        result.Dispose();
                    }
                    else
                    {
                        return result;
                    }
                }
                catch (global::System.Net.Http.HttpRequestException)
                {
                    result?.Dispose();
                    if (IsLastAttempt(i))
                        throw;
                }
                catch (global::System.Threading.Tasks.TaskCanceledException ex) when (ex.CancellationToken != cancellationToken) // catch "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing"
                {
                    result?.Dispose();
                    if (IsLastAttempt(i))
                        throw;
                }

                await global::System.Threading.Tasks.Task.Delay(delayHint is { } someDelay && someDelay > global::System.TimeSpan.Zero ? someDelay : defaultDelay, cancellationToken).ConfigureAwait(false);

                static bool IsLastAttempt(int i) => i >= MaxRetries;
            }
        }
    }
}
